name: character_repository
description: The Character Repository.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5

  character_api:
    path: ../../data/character_api
  duckduckgo:
    path: ../../models/duckduckgo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  mocktail: ^1.0.1

flutter: