name: shared
description: A Shared character viewer app.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  configuration:
    path: ../../models/configuration
  screens:
    path: ../../widgets/screens

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.sample.shared
        pluginClass: SharedPlugin
      ios:
        pluginClass: SharedPlugin
